### ISSUE TITLE
Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by tommoor** [outline/rich-markdown-editor#208]
Came from production error reporting – currently it's unclear what would cause this beyond it being related to the formatting toolbar.

![image](https://user-images.githubusercontent.com/380914/83041197-123ccd80-9ff5-11ea-9857-d75f8d068b89.png)

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
  at Error: Minified React error #185; visit (/docs/error-decoder.html)
  at Ig(./node_modules/react-dom/cjs/react-dom.production.min.js:230:18)
  at enqueueSetState(./node_modules/react-dom/cjs/react-dom.production.min.js:132:237)
  at setState(./node_modules/react/cjs/react.production.min.js:12:356)
  at componentDidUpdate(./node_modules/rich-markdown-editor/dist/lib/components/FloatingToolbar.js:81:1)
  at Ji(./node_modules/react-dom/cjs/react-dom.production.min.js:212:229)
  at b(./node_modules/react-dom/cjs/react-dom.production.min.js:255:222)
  at If(./node_modules/scheduler/cjs/scheduler.production.min.js:19:460)
  at cg(./node_modules/react-dom/cjs/react-dom.production.min.js:122:318)
  at Jj(./node_modules/react-dom/cjs/react-dom.production.min.js:248:370)
  at yj(./node_modules/react-dom/cjs/react-dom.production.min.js:239:376)
  at b(./node_modules/react-dom/cjs/react-dom.production.min.js:123:110)
  at If(./node_modules/scheduler/cjs/scheduler.production.min.js:19:460)
  at cg(./node_modules/react-dom/cjs/react-dom.production.min.js:122:318)
  at fg(./node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at gg(./node_modules/react-dom/cjs/react-dom.production.min.js:122:496)
  at Ig(./node_modules/react-dom/cjs/react-dom.production.min.js:230:94)
  at enqueueForceUpdate(./node_modules/react-dom/cjs/react-dom.production.min.js:133:76)
  at forceUpdate(./node_modules/react/cjs/react.production.min.js:12:443)
  at call(./node_modules/rich-markdown-editor/dist/lib/index.js:350:1)
  at dispatch(./node_modules/rich-markdown-editor/node_modules/prosemirror-view/dist/index.js:4837:29)
  at onSelectColumn(./node_modules/rich-markdown-editor/dist/lib/index.js:110:1)
  at HTMLAnchorElement.<anonymous>(./node_modules/rich-markdown-editor/dist/lib/nodes/TableHeadCell.js:71:1)
```

Sentry: https://sentry.io/organizations/outline-jl/issues/1685443357

**Comment by joshfeinsilber** [comment]
I am getting this error infrequently as well.

**Comment by lordkada** [comment]
I'm seeing this:

![Screenshot from 2020-06-19 18-57-35](https://user-images.githubusercontent.com/1006711/85160649-e3fe8680-b25e-11ea-8fe5-0b11518e42bb.png)

**Comment by tommoor** [comment]
Yep, that's the one – you can see in the stack trace there is a check for isEqual before setting state so this shouldn't be happening, I'm not sure what would cause the state to change every render loop – if you're able to reproduce this situation it would be useful to know how state is changing.

**Comment by lordkada** [comment]
Maybe I have a clue...
It looks that the problem occurs only if a set a default value, eg:

`
   return  <Editor  defaultValue={"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nulla orci, porta in purus convallis," +
                                " bibendum dignissim tellus. Duis quis magna at tellus pellentesque sagittis. Suspendisse erat odio, mollis nec est eget, pharetra fringilla eros. Mauris quis nibh turpis." +
                                " Suspendisse euismod bibendum metus placerat condimentum. Pellentesque nec quam porta, luctus turpis in, tempus eros." +
                                " Phasellus interdum, ligula nec ultrices dictum, purus nisi rutrum dolor, nec finibus magna neque vel velit." +
                                " Fusce quis eros bibendum, pellentesque dolor sit amet, pretium tellus." +
                                " Maecenas ex tellus, lacinia vel elementum eget, tristique eget augue. Sed aliquam justo scelerisque feugiat vulputate. In nec accumsan sapien."}/>;
`

**Comment by lordkada** [comment]
Hmmm...my last statement is not true...

**Comment by lordkada** [comment]
Ok, maybe one step ahead...
the check isEqual fails in my case just because the left property continues to change, like in a flip-flop never-ending loop.

As you can see from the first snapshots, the initial _newState_ is ~282 and _this.state_ is ~281

![Screenshot from 2020-06-22 11-41-07](https://user-images.githubusercontent.com/1006711/85274305-0e2e8f00-b47f-11ea-83f5-8249ebe65829.png)
![Screenshot from 2020-06-22 11-41-10](https://user-images.githubusercontent.com/1006711/85274314-1090e900-b47f-11ea-9228-e833be47e920.png)
 
Then they swap, _newState_ is ~281 and _this.state_ is ~282 (because the previous setState)

![Screenshot from 2020-06-22 11-41-23](https://user-images.githubusercontent.com/1006711/85274415-31f1d500-b47f-11ea-84ba-4e70c49ae079.png)
![Screenshot from 2020-06-22 11-41-26](https://user-images.githubusercontent.com/1006711/85274418-33bb9880-b47f-11ea-87ef-9c46b0579d41.png)

And again... in an infinite-breaking loop... ending with the exception above...

**Comment by tommoor** [comment]
I'll add rounding of the values, that should help stop the value bouncing back and forth.

**Comment by lordkada** [comment]
Hey, thanks for the patch, it's much better but the problem still occurs... :-(

In the case below I'm experiencing a flip-flop on two integers value (247 and 248) causing the never-ending loop leading to the usual error :-(

![Screenshot from 2020-06-23 09-42-19](https://user-images.githubusercontent.com/1006711/85375068-0ed62c80-b536-11ea-8e83-51dce5d03044.png)

**Comment by tommoor** [comment]
There was always a chance of that, I've still been unable to reproduce so I'm not sure what it is about your particular setup that makes it much more likely to happen – perhaps the position of the editor on the page? Nothing that goes into that calculation should be changing between render loops other than the users selection itself.

**Comment by lordkada** [comment]
Yes, it's not easy to catch... Look at this video: https://youtu.be/YuzuIuLhRyw
Sometimes I need to click a lot of times before it happens.

Please notice also the position of the toolbar, sometimes it's not aligned with the selected text... don't know if it somehow related or not...

**Comment by rohan-suri** [comment]
Any update on this? I am also getting the same error

**Comment by tommoor** [comment]
@rohan-suri – still never been able to reproduce despite it clearly being an issue in multiple situations 🤷 

Would love to fix it.

**Comment by mo-sharif** [comment]
fwiw this is happening for me in prod env and unable repo locally

**Comment by thenanyu** [comment]
@mo-sharif @rohan-suri — have either of you tried repro-ing locally with a the same doc data that exhibits this in prod?
